




cat_that: test.txt cat_that_in cat_that_out
	cat< test1.txt < testxx < test.txt > out1.txt > out2.txt > out_final.txt

cat_that_in:test.txt
	cat < test.txt

cat_that_out: test.txt
	cat test.txt > out2.txt